/**
 * Copyright (c) 2026 Gabriel Guerrer
 *
 * Distributed under the MIT license - See LICENSE for details
 */

/*
The health module implements entropy monitoring tests based on the NIST recommendations described
in:

M. Sonmez, E. Barker, J. Kelsey, K. McKay, M. Baish, and M. Boyle,
SP 800-90B: Recommendation for the Entropy Sources Used for Random Bit Generation,
National Institute of Standards and Technology (NIST), 2018.

Continuous health tests are performed by the rava_health_continuous methods during normal operation
for every generated byte. The firmware implements the two continuous tests recommended by NIST:
- Repetition count test (RCT)
- Adaptive proportion test (APT)

The repetition count test detects catastrophic failures that may cause the noise source to become
stuck at a constant output value for an extended period. The adaptive proportion test detects
significant entropy degradation caused by hardware faults or external disturbances affecting the
noise source.

The threshold values for both continuous tests are selected to correspond to a probability of 2^-20
of occurring by chance.

Continuous-test failures do not disable randomness generation. Instead, the firmware records the
detected errors, which can be queried by the user through the `COMM_HEALTH_CONTINUOUS_GET_ERRORS`
command id, allowing higher-level applications to monitor failure rates and take appropriate action
if necessary.
*/

#ifndef RAVA_HEALTH_CONTINUOUS_H
#define RAVA_HEALTH_CONTINUOUS_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include "rava_comm.h"

/* ===========================
 * RAVA HEALTH CONTINUOUS
 * =========================== */

void health_continuous_run_tests(const uint8_t *const byte_a, const uint8_t *const byte_b);

// COMM
void comm_health_continuous_get_errors(comm_interface_t *const comm);

#ifdef __cplusplus
}
#endif

#endif