/**
 * Copyright (c) 2026 Gabriel Guerrer
 *
 * Distributed under the MIT license - See LICENSE for details
 */

/*
This defines the communication protocol between the RAVA device and its host. The protocol
establishes a leader/follower architecture in which the host initiates communication by issuing
requests, and the RAVA device responds accordingly. Communication is implemented using framed
binary messages that can be transmitted over multiple transport layers, including USART, USB CDC,
SPI, Ethernet, and others.

The protocol frame has the following layout:

[SOF1][SOF2][REQ_ID][REQ_ERR][CMD_ID][R_LEN][D_LEN][...DATA][CRC16][...RAND]
   1     1      1       1        1      2      1     D_LEN     2     R_LEN

Where:
- SOF1, SOF2: Start-of-frame characters, defined respectively as '!' and '$'

- REQ_ID: Request identifier (256 possible values)
  - Enables an asynchronous request–response protocol in the host side

- REQ_ERR: Request error/status code
  - Defined in the `COMM_ERROR_IDS` enum

- CMD_ID: Command identifier
  - Command identifiers and their associated handler functions are defined in `rava_comm_handlers.h`

- R_LEN: Number of random payload bytes
  - The maximum value is defined by `RNG_GEN_MAX_NBYTES_PER_CORE`, which can be configure at build
    time using `-D RNG_GEN_MAX_NBYTES_PER_CORE=...`
  - Commands sent to the RAVA device must always use R_LEN == 0
  - Responses generated by the device may use R_LEN > 0 when returning randomness data

- D_LEN: Length of the header data field
  - Maximum value defined in `COMM_DATA_MAX_LEN`

- DATA: Optional message parameters data (D_LEN bytes)
  - The firmware serializes and deserializes C types using little-endian byte order.
  - Struct-based payloads must be packed to avoid padding bytes
  - On most 8-bit MCUs, structs are packed by default and typically do not require
    `__attribute__((packed))`
  - Host implementations must ensure: little-endian encoding, correct serialization/deserialization,
    and proper type sizes when reconstructing data structures

- CRC16: 16-bit CRC calculated over the message header
  - Calculated from REQ_ID through DATA, covering 7 + D_LEN bytes
  - Uses the CRC-16/CCITT (PPP/IrDA reflected variant) algorithm
  - Although some transports already include error detection mechanisms, the CRC ensures protocol
    consistency and also supports transports without built-in integrity checks, such as USART and
    SPI

- RAND: Optional random payload (R_LEN bytes)

- The total message length is: 10 + D_LEN + R_LEN bytes

The communication module assumes that applications implement a communication interface for message
transport, providing the methods defined in the `comm_interface_t`.
*/

#ifndef RAVA_COMM_H
#define RAVA_COMM_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdbool.h>
#include <stdint.h>

/* ===========================
 * RAVA COMM
 * =========================== */

#define COMM_SOF_A '!'
#define COMM_SOF_B '$'
#define COMM_HEADER_MIN_LEN 10
#define COMM_DATA_MAX_LEN 54
// #define COMM_RAND_MAX_LEN 32768  // Not used in the firmware side

enum COMM_STATE_IDS
{
  CS_WAIT_SOF_A,
  CS_WAIT_SOF_B,
  CS_READ_REQ_ID,
  CS_READ_REQ_ERROR,
  CS_READ_CMD_ID,
  CS_READ_RAND_LEN_A,
  CS_READ_RAND_LEN_B,
  CS_READ_DATA_LEN,
  CS_READ_DATA,
  CS_READ_CRC_A,
  CS_READ_CRC_B,
  // CS_READ_RAND,  // Not used in the firmware side
};

enum COMM_ERROR_IDS
{
  CE_OK,
  CE_INVALID_RAND_LEN,
  CE_INVALID_DATA_LEN,
  CE_INVALID_CRC,
  CE_INVALID_COMM_ID,
  CE_INVALID_INPUT_TYPES,
  CE_INVALID_INPUT_VALUES,
  CE_HEALTH_STARTUP_FAILED,
  CE_TIMER3_BUSY,
};

typedef struct comm_state_t
{
  uint8_t id, data_idx;
  // uint8_t rand_idx;  // Not used in the firmware side
  uint16_t crc, crc_rcv;
} comm_state_t;

typedef struct comm_message_t
{
  uint16_t rand_len;
  uint8_t req_id, req_error, comm_id, data_len;
  uint8_t data[COMM_DATA_MAX_LEN];
  // uint8_t rand[2*RNG_GEN_MAX_NBYTES_PER_CORE];  // Not used in the firmware side
} comm_message_t;

typedef struct comm_interface_t
{
  bool (*const read)(uint8_t *const value);
  void (*const write)(uint8_t value);
  void (*const write_buf)(const uint8_t *const buffer, uint8_t length);
  void (*const flush)(void);

  struct comm_state_t state;
  struct comm_message_t msg;
} comm_interface_t;

bool parse_rava_byte(struct comm_state_t *const state, struct comm_message_t *const msg, uint8_t byte);
bool read_rava_msg(comm_interface_t *const comm_if);
void send_rava_msg_header(comm_interface_t *const comm_if, uint8_t req_error, uint16_t rand_len, uint8_t data_len, const void *const data);

#ifdef __cplusplus
}
#endif

#endif