/**
 * Copyright (c) 2026 Gabriel Guerrer
 *
 * Distributed under the MIT license - See LICENSE for details
 */

#include "rava_health_continuous.h"

#define H_CONTINUOUS_REPETITION_COUNT_CUTOFF 4 // 1 + 20 / 7.8
#define H_CONTINUOUS_ADAPTIVE_PROPORTION_W 512U
#define H_CONTINUOUS_ADAPTIVE_PROPORTION_CUTOFF 13 // 1 + binom(512, 2**(-7.8)).ppf(1-2**(-20))

static uint8_t byte_prev_a=0, byte_prev_b=0;

// Repetition count vars
static uint8_t nrc_cutoff = H_CONTINUOUS_REPETITION_COUNT_CUTOFF;
static uint8_t nrc_counter_a = 1, nrc_counter_b = 1;

// Adaptive proportion vars
static uint8_t nap_cutoff = H_CONTINUOUS_ADAPTIVE_PROPORTION_CUTOFF;
static uint16_t nap_iter_a = 0, nap_iter_b = 0;
static uint8_t nap_counter_a = 1, nap_counter_b = 1;
static uint8_t nap_target_a, nap_target_b;

// Test Results
typedef struct health_continuous_tests_t
{
  uint16_t count_a, count_b;
} health_continuous_tests_t;

static health_continuous_tests_t nrc_error = {0}, nap_error = {0};

// Functions
static void health_continuous_reset_errors(void);
static void nist_repetition_count(const uint8_t *const byte_a, const uint8_t *const byte_b);
static void nist_adaptive_proportion(const uint8_t *const byte_a, const uint8_t *const byte_b);


/* ===========================
 * RAVA HEALTH CONTINUOUS
 * =========================== */

/*
Executes the continuous health tests using random bytes generated by cores A and B.
*/
void health_continuous_run_tests(const uint8_t *const byte_a, const uint8_t *const byte_b)
{
  // Run tests
  nist_repetition_count(byte_a, byte_b);
  nist_adaptive_proportion(byte_a, byte_b);
}

/*
Resets the continuous health errors.
*/
static void health_continuous_reset_errors(void)
{
  nrc_error.count_a = 0;
  nrc_error.count_b = 0;

  nap_error.count_a = 0;
  nap_error.count_b = 0;
}

/*
The repetition count test detects catastrophic failures that may cause the noise source to become
stuck at a constant output value for an extended period.
*/
static void nist_repetition_count(const uint8_t *const byte_a, const uint8_t *const byte_b)
{
  // RNG A
  if (*byte_a == byte_prev_a) {
    nrc_counter_a++;

    if (nrc_counter_a >= nrc_cutoff) {
      nrc_error.count_a++; // Count error on rnd_a
    }
  }
  else {
    byte_prev_a = *byte_a;
    nrc_counter_a = 1;
    }

  // RNG B
  if (*byte_b == byte_prev_b) {
    nrc_counter_b++;

    if (nrc_counter_b >= nrc_cutoff) {
      nrc_error.count_b++; // Count error on rnd_b
    }
  }
  else {
    byte_prev_b = *byte_b;
    nrc_counter_b = 1;
    }
}

/*
The adaptive proportion test detects significant entropy degradation caused by hardware faults or
external disturbances affecting the noise source.
*/
static void nist_adaptive_proportion(const uint8_t *const byte_a, const uint8_t *const byte_b)
{
  // RNG A
  if (nap_iter_a == 0) {
    nap_target_a = *byte_a;
    nap_counter_a = 1;
    nap_iter_a++;
  }
  else {
    if (*byte_a == nap_target_a) {
      nap_counter_a++;

      if (nap_counter_a == nap_cutoff)
        nap_error.count_a++; // Count error on rnd_a
    }

    nap_iter_a++;
    if (nap_iter_a == H_CONTINUOUS_ADAPTIVE_PROPORTION_W)
      nap_iter_a = 0;
  }

  // RNG B
  if (nap_iter_b == 0) {
    nap_target_b = *byte_b;
    nap_counter_b = 1;
    nap_iter_b++;
  }
  else {
    if (*byte_b == nap_target_b) {
      nap_counter_b++;

      if (nap_counter_b == nap_cutoff)
        nap_error.count_b++; // Count error on rnd_b
    }

    nap_iter_b++;
    if (nap_iter_b == H_CONTINUOUS_ADAPTIVE_PROPORTION_W)
      nap_iter_b = 0;
  }
}

/* ===========================
 * COMM
 * =========================== */

/*
Processes the request to send the overall result of the continuous health tests together with the
error counts for each individual test.
*/
void comm_health_continuous_get_errors(comm_interface_t *const comm)
{
  // IO Structure
  //typedef struct {} data_in_t;
  typedef struct {bool has_error; health_continuous_tests_t nrc_error, nap_error;} data_out_t;
  //data_in_t  data_in;
  data_out_t data_out;

  // Process Output
  data_out.has_error = (nrc_error.count_a > 0 || nrc_error.count_b > 0 || nap_error.count_a > 0 || nap_error.count_b > 0 ) ? true : false;
  data_out.nrc_error = nrc_error;
  data_out.nap_error = nap_error;

  // Send
  send_rava_msg_header(comm, CE_OK, 0, sizeof(data_out), &data_out);

  // Reset errors
  health_continuous_reset_errors();
}